#include "types.h"
#include "param.h"
#include "memlayout.h"
#include "riscv.h"
#include "spinlock.h"
#include "defs.h"
#include "shmem.h"
#include "proc.h"

/*
 * icc.c -- AMP inter-core communication driver for xv6.
 *
 * Stage 5 turns the stage-3/4 shared-memory rings into a small endpoint API:
 *
 *   FreeRTOS -> xv6:
 *     mailbox interrupt -> icc_notify_recv()
 *       -> drain to_xv6 ring -> endpoint slot -> wakeup()
 *
 *   xv6 -> FreeRTOS:
 *     syscall -> icc_send()
 *       -> fill to_rtos ring -> advance tail -> mailbox doorbell
 *
 * xv6 does not run arbitrary callbacks from interrupt context.  Instead, the
 * interrupt stores a message in a pre-registered endpoint and wakes any process
 * sleeping in icc_recv().  This matches the normal xv6 console/pipe style and
 * keeps endpoint ownership easy to reason about.
 */
#define ICC_MAX_ENDPOINTS 8

struct icc_endpoint {
  uint32 ep;
  int has_msg;
  struct shmem_msg msg;
  struct spinlock lock;
};

static struct icc_endpoint icc_eps[ICC_MAX_ENDPOINTS];
static struct spinlock icc_send_lock;

static struct icc_endpoint*
icc_find_ep(uint32 ep)
{
  for(int i = 0; i < ICC_MAX_ENDPOINTS; i++){
    if(icc_eps[i].ep == ep)
      return &icc_eps[i];
  }
  return 0;
}

static void
copy_msg_from_volatile(struct shmem_msg *dst, volatile struct shmem_msg *src)
{
  uint8 *d = (uint8*)dst;
  volatile uint8 *s = (volatile uint8*)src;

  for(uint i = 0; i < sizeof(*dst); i++)
    d[i] = s[i];
}

static void
clear_volatile_msg(volatile struct shmem_msg *msg)
{
  volatile uint8 *p = (volatile uint8*)msg;

  for(uint i = 0; i < sizeof(*msg); i++)
    p[i] = 0;
}

static void
payload_to_string(char *dst, uint dst_size, struct shmem_msg *msg)
{
  uint len = msg->len;

  if(dst_size == 0)
    return;
  if(len >= dst_size)
    len = dst_size - 1;
  if(len > sizeof(msg->payload))
    len = sizeof(msg->payload);

  memmove(dst, msg->payload, len);
  dst[len] = '\0';
}

static void
icc_drop_pending(uint32 ep)
{
  struct icc_endpoint *e = icc_find_ep(ep);

  if(e == 0)
    return;

  /*
   * The current stage has one test endpoint and one message slot.  Drop any
   * stale unsolicited/test message before a new request so icctest waits for
   * the reply generated by the request it just sent.
   */
  acquire(&e->lock);
  e->has_msg = 0;
  release(&e->lock);
}

void
icc_init(void)
{
  for(int i = 0; i < ICC_MAX_ENDPOINTS; i++){
    icc_eps[i].ep = 0;
    icc_eps[i].has_msg = 0;
    initlock(&icc_eps[i].lock, "icc_ep");
  }

  /*
   * Static endpoint registration avoids table mutation while mailbox interrupt
   * handling may be active.  More endpoints can be added here in later stages.
   */
  icc_eps[0].ep = SHMEM_EP_XV6_TEST;

  initlock(&icc_send_lock, "icc_send");
  printf("icc: init endpoints=%d local_ep=%x\n",
         ICC_MAX_ENDPOINTS, SHMEM_EP_XV6_TEST);
}

void
icc_notify_recv(uint32 reason)
{
  if(reason != SHMEM_DOORBELL_CH0)
    return;

  if(SHMEM_CTRL_BASE->magic != SHMEM_MAGIC ||
     SHMEM_CTRL_BASE->version != SHMEM_VERSION)
    return;

  for(;;){
    uint32 head = SHMEM_CTRL_BASE->to_xv6_head;
    uint32 tail = SHMEM_CTRL_BASE->to_xv6_tail;
    uint32 idx;
    struct shmem_msg msg;
    char payload[SHMSG_PAYLOAD_SIZE + 1];
    struct icc_endpoint *e;

    if(head == tail)
      break;

    idx = head % SHMSG_SLOT_NUM;

    /*
     * Copy by value before advancing head.  Once head moves, the slot is
     * returned to FreeRTOS and task context must not depend on it anymore.
     */
    __sync_synchronize();
    copy_msg_from_volatile(&msg, &SHMEM_TO_XV6_BASE[idx]);

    __sync_synchronize();
    SHMEM_CTRL_BASE->to_xv6_head = head + 1;

    payload_to_string(payload, sizeof(payload), &msg);
    e = icc_find_ep(msg.dst_ep);
    if(e != 0){
      acquire(&e->lock);
      if(e->has_msg){
        printf("icc rx: overwrite ep=%x old_cookie=%x new_cookie=%x\n",
               msg.dst_ep, e->msg.cookie, msg.cookie);
      }
      e->msg = msg;
      e->has_msg = 1;
      wakeup(e);
      release(&e->lock);

      printf("icc rx: dispatched idx=%d ep=%x src=%x cmd=%x cookie=%x payload=%s\n",
             idx, msg.dst_ep, msg.src_ep, msg.cmd, msg.cookie, payload);
    } else {
      printf("icc rx: no endpoint idx=%d dst=%x src=%x cmd=%x cookie=%x payload=%s\n",
             idx, msg.dst_ep, msg.src_ep, msg.cmd, msg.cookie, payload);
    }
  }
}

int
icc_send(uint32 dst_ep, uint32 cmd, const char *payload, uint32 len,
         uint32 cookie)
{
  uint32 head;
  uint32 tail;
  uint32 idx;
  uint32 copy_len;
  volatile struct shmem_msg *slot;

  if(SHMEM_CTRL_BASE->magic != SHMEM_MAGIC ||
     SHMEM_CTRL_BASE->version != SHMEM_VERSION){
    printf("icc tx: shmem not ready magic=%x version=%d\n",
           SHMEM_CTRL_BASE->magic, SHMEM_CTRL_BASE->version);
    return -1;
  }

  if(len > SHMSG_PAYLOAD_SIZE)
    len = SHMSG_PAYLOAD_SIZE;

  /*
   * SHMEM_EP_XV6_TEST is the only local endpoint in this stage.  Clear old
   * replies or unsolicited test packets before submitting a new request, so a
   * following icc_recv() observes the message caused by this send.
   */
  icc_drop_pending(SHMEM_EP_XV6_TEST);

  acquire(&icc_send_lock);

  head = SHMEM_CTRL_BASE->to_rtos_head;
  tail = SHMEM_CTRL_BASE->to_rtos_tail;
  if(tail - head >= SHMSG_SLOT_NUM){
    release(&icc_send_lock);
    printf("icc tx: to_rtos full head=%d tail=%d\n", head, tail);
    return -1;
  }

  idx = tail % SHMSG_SLOT_NUM;
  slot = &SHMEM_TO_RTOS_BASE[idx];
  clear_volatile_msg(slot);

  slot->src_ep = SHMEM_EP_XV6_TEST;
  slot->dst_ep = dst_ep;
  slot->cmd = cmd;
  slot->cookie = cookie;
  slot->flags = 0;

  for(copy_len = 0; copy_len < len; copy_len++)
    slot->payload[copy_len] = payload[copy_len];
  slot->len = copy_len;

  __sync_synchronize();
  SHMEM_CTRL_BASE->to_rtos_tail = tail + 1;

  release(&icc_send_lock);

  printf("icc tx: slot=%d dst=%x cmd=%x cookie=%x len=%d -> FreeRTOS\n",
         idx, dst_ep, cmd, cookie, copy_len);
  mailbox_ring_to_rtos(SHMEM_DOORBELL_CH0);
  return 0;
}

int
icc_recv(uint32 ep, struct shmem_msg *out)
{
  struct icc_endpoint *e = icc_find_ep(ep);

  if(e == 0)
    return -1;

  acquire(&e->lock);
  while(!e->has_msg && !killed(myproc()))
    sleep(e, &e->lock);

  if(killed(myproc())){
    release(&e->lock);
    return -1;
  }

  *out = e->msg;
  e->has_msg = 0;
  release(&e->lock);
  return 0;
}
