#include "types.h"
#include "param.h"
#include "memlayout.h"
#include "riscv.h"
#include "spinlock.h"
#include "defs.h"
#include "shmem.h"
#include "proc.h"

/*
 * icc.c -- AMP inter-core communication driver for xv6.
 *
 * Stage 5 turns the stage-3/4 shared-memory rings into a small endpoint API:
 *
 *   FreeRTOS -> xv6:
 *     mailbox interrupt -> icc_notify_recv()
 *       -> drain to_xv6 ring -> endpoint slot -> wakeup()
 *
 *   xv6 -> FreeRTOS:
 *     syscall -> icc_send()
 *       -> fill to_rtos ring -> advance tail -> mailbox doorbell
 *
 * Stage 6 adds a synchronous RPC layer on top of the same rings.  The caller
 * submits one rpccall() syscall; the kernel allocates a cookie, sends the
 * request, and sleeps on a pending slot until icc_notify_recv() sees the
 * matching reply cookie.
 *
 * xv6 does not run arbitrary callbacks from interrupt context.  Instead, the
 * interrupt stores a message in a pre-registered endpoint or RPC pending slot
 * and wakes the sleeping process.  This matches the normal xv6 console/pipe
 * style and keeps endpoint ownership easy to reason about.
 */
#define ICC_MAX_ENDPOINTS 8
#define ICC_RPC_MAX_PENDING 4

struct icc_endpoint {
  uint32 ep;
  int has_msg;
  struct shmem_msg msg;
  struct spinlock lock;
};

struct icc_rpc_pending {
  uint32 cookie;
  int in_use;
  int has_reply;
  struct shmem_msg reply;
  struct spinlock lock;
};

static struct icc_endpoint icc_eps[ICC_MAX_ENDPOINTS];
static struct spinlock icc_send_lock;
static struct icc_rpc_pending icc_rpc_table[ICC_RPC_MAX_PENDING];
static struct spinlock icc_rpc_lock;
static uint32 icc_rpc_next_cookie = 0x6000;

static struct icc_endpoint*
icc_find_ep(uint32 ep)
{
  for(int i = 0; i < ICC_MAX_ENDPOINTS; i++){
    if(icc_eps[i].ep == ep)
      return &icc_eps[i];
  }
  return 0;
}

static void
copy_msg_from_volatile(struct shmem_msg *dst, volatile struct shmem_msg *src)
{
  uint8 *d = (uint8*)dst;
  volatile uint8 *s = (volatile uint8*)src;

  for(uint i = 0; i < sizeof(*dst); i++)
    d[i] = s[i];
}

static void
clear_volatile_msg(volatile struct shmem_msg *msg)
{
  volatile uint8 *p = (volatile uint8*)msg;

  for(uint i = 0; i < sizeof(*msg); i++)
    p[i] = 0;
}

static void
payload_to_string(char *dst, uint dst_size, struct shmem_msg *msg)
{
  uint len = msg->len;

  if(dst_size == 0)
    return;
  if(len >= dst_size)
    len = dst_size - 1;
  if(len > sizeof(msg->payload))
    len = sizeof(msg->payload);

  memmove(dst, msg->payload, len);
  dst[len] = '\0';
}

static void
icc_drop_pending(uint32 ep)
{
  struct icc_endpoint *e = icc_find_ep(ep);

  if(e == 0)
    return;

  /*
   * The current stage has one test endpoint and one message slot.  Drop any
   * stale unsolicited/test message before a new request so icctest waits for
   * the reply generated by the request it just sent.
   */
  acquire(&e->lock);
  e->has_msg = 0;
  release(&e->lock);
}

static struct icc_rpc_pending*
icc_rpc_alloc(void)
{
  struct icc_rpc_pending *p = 0;

  /*
   * Table allocation and cookie generation are serialized separately from the
   * per-slot lock.  The slot is marked in_use before the request is sent, so an
   * early reply can be matched even if it arrives before the caller sleeps.
   */
  acquire(&icc_rpc_lock);
  for(int i = 0; i < ICC_RPC_MAX_PENDING; i++){
    if(!icc_rpc_table[i].in_use){
      p = &icc_rpc_table[i];
      acquire(&p->lock);
      p->in_use = 1;
      p->has_reply = 0;
      p->cookie = icc_rpc_next_cookie++;
      memset(&p->reply, 0, sizeof(p->reply));
      release(&p->lock);
      break;
    }
  }
  release(&icc_rpc_lock);

  return p;
}

static void
icc_rpc_free(struct icc_rpc_pending *p)
{
  acquire(&icc_rpc_lock);
  acquire(&p->lock);
  p->in_use = 0;
  p->has_reply = 0;
  p->cookie = 0;
  memset(&p->reply, 0, sizeof(p->reply));
  release(&p->lock);
  release(&icc_rpc_lock);
}

static int
icc_rpc_try_match(struct shmem_msg *msg, char *payload)
{
  for(int i = 0; i < ICC_RPC_MAX_PENDING; i++){
    struct icc_rpc_pending *p = &icc_rpc_table[i];

    acquire(&p->lock);
    if(p->in_use && p->cookie == msg->cookie){
      p->reply = *msg;
      p->has_reply = 1;
      wakeup(p);
      release(&p->lock);

      printf("icc rx: rpc reply matched cookie=%x payload=%s\n",
             msg->cookie, payload);
      return 1;
    }
    release(&p->lock);
  }

  return 0;
}

void
icc_init(void)
{
  for(int i = 0; i < ICC_MAX_ENDPOINTS; i++){
    icc_eps[i].ep = 0;
    icc_eps[i].has_msg = 0;
    initlock(&icc_eps[i].lock, "icc_ep");
  }

  /*
   * Static endpoint registration avoids table mutation while mailbox interrupt
   * handling may be active.  More endpoints can be added here in later stages.
   */
  icc_eps[0].ep = SHMEM_EP_XV6_TEST;

  initlock(&icc_send_lock, "icc_send");

  for(int i = 0; i < ICC_RPC_MAX_PENDING; i++){
    icc_rpc_table[i].cookie = 0;
    icc_rpc_table[i].in_use = 0;
    icc_rpc_table[i].has_reply = 0;
    memset(&icc_rpc_table[i].reply, 0, sizeof(icc_rpc_table[i].reply));
    initlock(&icc_rpc_table[i].lock, "icc_rpc");
  }
  initlock(&icc_rpc_lock, "icc_rpc_tbl");

  printf("icc: init endpoints=%d local_ep=%x rpc_pending=%d\n",
         ICC_MAX_ENDPOINTS, SHMEM_EP_XV6_TEST, ICC_RPC_MAX_PENDING);
}

void
icc_notify_recv(uint32 reason)
{
  if(reason != SHMEM_DOORBELL_CH0)
    return;

  if(SHMEM_CTRL_BASE->magic != SHMEM_MAGIC ||
     SHMEM_CTRL_BASE->version != SHMEM_VERSION)
    return;

  for(;;){
    uint32 head = SHMEM_CTRL_BASE->to_xv6_head;
    uint32 tail = SHMEM_CTRL_BASE->to_xv6_tail;
    uint32 idx;
    struct shmem_msg msg;
    char payload[SHMSG_PAYLOAD_SIZE + 1];
    struct icc_endpoint *e;

    if(head == tail)
      break;

    idx = head % SHMSG_SLOT_NUM;

    /*
     * Copy by value before advancing head.  Once head moves, the slot is
     * returned to FreeRTOS and task context must not depend on it anymore.
     */
    __sync_synchronize();
    copy_msg_from_volatile(&msg, &SHMEM_TO_XV6_BASE[idx]);

    __sync_synchronize();
    SHMEM_CTRL_BASE->to_xv6_head = head + 1;

    payload_to_string(payload, sizeof(payload), &msg);

    /*
     * Stage 6 RPC replies share the same to_xv6 ring as asynchronous endpoint
     * messages.  A live RPC call owns a unique cookie, so check pending slots
     * first.  Unmatched messages fall through to the stage-5 endpoint path.
     */
    if(icc_rpc_try_match(&msg, payload))
      continue;

    e = icc_find_ep(msg.dst_ep);
    if(e != 0){
      acquire(&e->lock);
      if(e->has_msg){
        printf("icc rx: overwrite ep=%x old_cookie=%x new_cookie=%x\n",
               msg.dst_ep, e->msg.cookie, msg.cookie);
      }
      e->msg = msg;
      e->has_msg = 1;
      wakeup(e);
      release(&e->lock);

      printf("icc rx: dispatched idx=%d ep=%x src=%x cmd=%x cookie=%x payload=%s\n",
             idx, msg.dst_ep, msg.src_ep, msg.cmd, msg.cookie, payload);
    } else {
      printf("icc rx: no endpoint idx=%d dst=%x src=%x cmd=%x cookie=%x payload=%s\n",
             idx, msg.dst_ep, msg.src_ep, msg.cmd, msg.cookie, payload);
    }
  }
}

int
icc_send(uint32 dst_ep, uint32 cmd, const char *payload, uint32 len,
         uint32 cookie)
{
  uint32 head;
  uint32 tail;
  uint32 idx;
  uint32 copy_len;
  volatile struct shmem_msg *slot;

  if(SHMEM_CTRL_BASE->magic != SHMEM_MAGIC ||
     SHMEM_CTRL_BASE->version != SHMEM_VERSION){
    printf("icc tx: shmem not ready magic=%x version=%d\n",
           SHMEM_CTRL_BASE->magic, SHMEM_CTRL_BASE->version);
    return -1;
  }

  if(len > SHMSG_PAYLOAD_SIZE)
    len = SHMSG_PAYLOAD_SIZE;

  /*
   * SHMEM_EP_XV6_TEST is the only local endpoint in this stage.  Clear old
   * replies or unsolicited test packets before submitting a new request, so a
   * following icc_recv() observes the message caused by this send.
   */
  icc_drop_pending(SHMEM_EP_XV6_TEST);

  acquire(&icc_send_lock);

  head = SHMEM_CTRL_BASE->to_rtos_head;
  tail = SHMEM_CTRL_BASE->to_rtos_tail;
  if(tail - head >= SHMSG_SLOT_NUM){
    release(&icc_send_lock);
    printf("icc tx: to_rtos full head=%d tail=%d\n", head, tail);
    return -1;
  }

  idx = tail % SHMSG_SLOT_NUM;
  slot = &SHMEM_TO_RTOS_BASE[idx];
  clear_volatile_msg(slot);

  slot->src_ep = SHMEM_EP_XV6_TEST;
  slot->dst_ep = dst_ep;
  slot->cmd = cmd;
  slot->cookie = cookie;
  slot->flags = 0;

  for(copy_len = 0; copy_len < len; copy_len++)
    slot->payload[copy_len] = payload[copy_len];
  slot->len = copy_len;

  __sync_synchronize();
  SHMEM_CTRL_BASE->to_rtos_tail = tail + 1;

  release(&icc_send_lock);

  printf("icc tx: slot=%d dst=%x cmd=%x cookie=%x len=%d -> FreeRTOS\n",
         idx, dst_ep, cmd, cookie, copy_len);
  mailbox_ring_to_rtos(SHMEM_DOORBELL_CH0);
  return 0;
}

int
icc_recv(uint32 ep, struct shmem_msg *out)
{
  struct icc_endpoint *e = icc_find_ep(ep);

  if(e == 0)
    return -1;

  acquire(&e->lock);
  while(!e->has_msg && !killed(myproc()))
    sleep(e, &e->lock);

  if(killed(myproc())){
    release(&e->lock);
    return -1;
  }

  *out = e->msg;
  e->has_msg = 0;
  release(&e->lock);
  return 0;
}

int
icc_rpc_call(uint32 dst_ep, uint32 cmd, const char *payload, uint32 len,
             char *reply_buf, uint32 reply_max, uint32 *reply_len)
{
  struct icc_rpc_pending *p;
  uint32 cookie;
  uint32 copy_len;

  if(reply_len == 0)
    return -1;

  if(len > SHMSG_PAYLOAD_SIZE)
    len = SHMSG_PAYLOAD_SIZE;
  if(reply_max > SHMSG_PAYLOAD_SIZE)
    reply_max = SHMSG_PAYLOAD_SIZE;

  p = icc_rpc_alloc();
  if(p == 0){
    printf("icc rpc: pending table full\n");
    return -1;
  }

  acquire(&p->lock);
  cookie = p->cookie;
  release(&p->lock);

  if(icc_send(dst_ep, cmd, payload, len, cookie) < 0){
    icc_rpc_free(p);
    return -1;
  }

  /*
   * The reply may arrive before we reach sleep().  Because icc_rpc_alloc()
   * marks the slot in_use before icc_send(), the interrupt path will set
   * has_reply and wake this slot; the while condition handles both orders.
   */
  acquire(&p->lock);
  while(!p->has_reply && !killed(myproc()))
    sleep(p, &p->lock);

  if(killed(myproc())){
    release(&p->lock);
    icc_rpc_free(p);
    return -1;
  }

  copy_len = p->reply.len;
  if(copy_len > reply_max)
    copy_len = reply_max;
  if(copy_len > SHMSG_PAYLOAD_SIZE)
    copy_len = SHMSG_PAYLOAD_SIZE;

  if(copy_len > 0)
    memmove(reply_buf, p->reply.payload, copy_len);
  *reply_len = copy_len;
  release(&p->lock);

  icc_rpc_free(p);
  return 0;
}
